### ISSUE TITLE
`gotemplate --version` still reports 2.7.4 in version 3.9.1 

### ISSUE THREAD

**Issue by giorgiga** [coveooss/gotemplate#262]
Come on, guys :)

**Comment by giorgiga** [comment]
The culprit is right there in main.go:

https://github.com/coveooss/gotemplate/blob/45dbe90c10b2f1b5e8182601ce887b65346e7ef3/main.go#L28

I'm not sending a PR because I wouldn't know what version to replace 2.7.4 with (I guess 3.9.2?)

**Comment by jocgir** [comment]
Thank you for the catch.

In fact, the problem was caused by the fact that the variable was no longer public version instead of Version.

The GitHub action goreleaser shoult take care of it.

**Comment by jocgir** [comment]
Hello @giorgiga,

The issue wasn’t what I initially thought. The root cause lies in your build process.

If you download our pre-built version of the executable, the version is reported correctly because we use `goreleaser` to publish our binaries, which automatically sets the `main.version` based on the tag that triggered the build.

However, if you’re compiling it yourself, you’ll need to provide the `-ldflags` option:

```
go build -o gotemplate -ldflags "-X main.version=1.2.3"
```

**Comment by jocgir** [comment]
I replaced the version string by:

`var version = "major.minor.patch # locally built, should be replaced by the build process with -ldflags \"-X main.version=<version number>\""`

in #264

**Comment by giorgiga** [comment]
Thanks - I fixed the build for NixOS.

Not my business, but... to avoid this same issue with other distros as they start to package gotemplate, I'd recommend you document the build process :)
